### ISSUE TITLE
README

### ISSUE THREAD

**Issue by matthew4444** [ImagicalCorp/Firecracker#1]
can i use this plugin on my plugins repo plz?

**Comment by thebigsmileXD** [comment]
Specify/explain what you mean.

**Comment by matthew4444** [comment]
can i upload this plugin to my site ill give credit

**Comment by thebigsmileXD** [comment]
As download link use my website please. http://wolvesfortress.de/de_DE/plugins/Firecracker.php

**Comment by matthew4444** [comment]
kk

**Comment by thebigsmileXD** [comment]
The plugin now moved to https://github.com/thebigsmileXD/Firecracker

**Comment by matthew4444** [comment]
kk im adding it ,thx u are on the universmakers plugin team,srry i frohgot to add u to the new endkingdom repo org

**Comment by thebigsmileXD** [comment]
Won't join other repos anymore. I am already busy with ClearSky, my plugins and Reallife and creating a csgo map

**Comment by matthew4444** [comment]
ohh kk srry
